version: 0.2

env:
  variables:
    IMAGE_TAG: latest
    AWS_REGION: us-east-1
    REPOSITORY_URI: 834585058280.dkr.ecr.us-east-1.amazonaws.com/customers-service

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installation de Maven et Docker..."
      - apt-get update
      - apt-get install -y maven docker

  pre_build:
    commands:
      - echo "Connexion à Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Compilation de l'application Spring Boot..."
      - mvn clean package -DskipTests
      - echo "Construction de l'image Docker..."
      - docker build -t customers-service .
      - docker tag customers-service:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Push de l'image Docker vers ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Déploiement terminé avec succès."

artifacts:
  files:
    - target/*.jar
#